name: ${project.name}
main: ${mainClass}
version: ${project.version}
authors: [JerryWood, TekkitCommando, Phillmac, Jerzean, mercurialmusic]
description: ${project.description}
website:  http://woominecraft.com
api-version: "1.20"
libraries:
  - com.squareup.okhttp3:okhttp:3.13.1
commands:
  woo:
    description: Check
    usage: |
        /<command> check - check for donations.
permissions:
  woo.admin:
    default: op
    description: Allows the player (or console) to use the woo commands.
